# -*- coding: utf-8 -*-
"""Variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6oeQf5xQuzGRobXbtIVQujnv-pZ0Ro4

# 1. Create a variable to store your name and print it.
"""

name = "Vasudev"
print(name)

"""# 2. Assign your age to a variable and print it."""

age = 31
print(age)

"""### 3. Create a variable to store the price of an item and another variable to store the quantity. Calculate and print the total cost."""

price_per_item = 20.99
quantity = 3
total_cost = price_per_item * quantity
print(total_cost)

"""# 4. Store the result of an addition operation (e.g., 5 + 7) in a variable and print the result."""

result = 5 + 7
print(result)

"""# 5. Create two variables, x and y, and assign them integer values. Swap their values and print both variables."""

x = 10
y = 20
x, y = y, x
print("x,y=",x,y)

"""# 6. Create a variable to store your favorite color and print a message including the color."""

favorite_color = "blue"
print("My favorite color is",favorite_color)

"""# 7. Assign a boolean value to a variable indicating whether you are a student (True or False). Print the value of the variable."""

is_student = True
print(is_student)

"""# 8. Store a decimal number in a variable and print it rounded to two decimal places."""

decimal_number = 5.6789
rounded_number = round(decimal_number, 2)
print(rounded_number)

"""# 9. Create a variable to store your height in meters and another variable to store your weight in kilograms. Print a message that includes both values."""

height = 1.75  # Height in meters
weight = 70  # Weight in kg
print("Height in Meter=",height,"\nWeight in Kg=",weight)

"""# 10. Create a variable to store a greeting message, and then concatenate it with another message to form a full sentence. Print the full sentence.

"""

greeting = "Hello"
full_sentence = greeting + ", welcome to the Bangalore"
print(full_sentence)